In [5]:
# red라는 글자와 blue라는 글자를 20개 만들기
# red , blue , red , blue
print(rep(c("red","blue"),20))

# 135 12345678910 13579 123123 
print(c(seq(1,5,2), 1:10 , seq(1,9,2) , rep(1:3,2)))
print(c(c(1,3,5), 1:10 , seq(1,9,2) , rep(1:3,2)))

 [1] "red"  "blue" "red"  "blue" "red"  "blue" "red"  "blue" "red"  "blue"
[11] "red"  "blue" "red"  "blue" "red"  "blue" "red"  "blue" "red"  "blue"
[21] "red"  "blue" "red"  "blue" "red"  "blue" "red"  "blue" "red"  "blue"
[31] "red"  "blue" "red"  "blue" "red"  "blue" "red"  "blue" "red"  "blue"
 [1]  1  3  5  1  2  3  4  5  6  7  8  9 10  1  3  5  7  9  1  2  3  1  2  3
 [1]  1  3  5  1  2  3  4  5  6  7  8  9 10  1  3  5  7  9  1  2  3  1  2  3


In [6]:
# 데이터프레임
# iris의 1~5번째 줄의 데이터만 추출해서 변수(데이터프레임)로 만들기
head(iris, 5)
irisHead <- iris[1:5,] # 행열 지정해서 불러오기 DB이름[ 행 , 열 ] / 전체를 불러올땐 공백
iris[1:5 , c(1,3)]

Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa

Sepal.Length Petal.Length
1 5.1          1.4         
2 4.9          1.4         
3 4.7          1.3         
4 4.6          1.5         
5 5.0          1.4

In [7]:
# 행과 열을 뒤집는다.
# 횡(가로)으로 긴 데이터는 행열을 뒤집어줘야 한다. 횡으로 긴 데이터는 분석프로그램 사용 불가능하다.
t(irisHead)

1      2      3      4      5     
Sepal.Length 5.1    4.9    4.7    4.6    5.0   
Sepal.Width  3.5    3.0    3.2    3.1    3.6   
Petal.Length 1.4    1.4    1.3    1.5    1.4   
Petal.Width  0.2    0.2    0.2    0.2    0.2   
Species      setosa setosa setosa setosa setosa

In [8]:
# iris에서 150개 데이터 중 10번 부터 10씩 증가하여 15개만 Sampling하기
iris[seq(0,nrow(iris),10),]
# 정렬이 잘 되어 있는지, 데이터의 대략적인 모습을 볼 수 있다. 어떤 컬럼을 Feature로 쓸 수 있을지
# Feature 특징, 머신러닝의 타겟 , ML[Target] <- [Feature,@,@,@,] 분석가가 피쳐를 정해줌, 따라서 데이터가 약간 적어도 가능 / 딥러닝은 피쳐를 정해주지 않는다.

Sepal.Length Sepal.Width Petal.Length Petal.Width Species   
10  4.9          3.1         1.5          0.1         setosa    
20  5.1          3.8         1.5          0.3         setosa    
30  4.7          3.2         1.6          0.2         setosa    
40  5.1          3.4         1.5          0.2         setosa    
50  5.0          3.3         1.4          0.2         setosa    
60  5.2          2.7         3.9          1.4         versicolor
70  5.6          2.5         3.9          1.1         versicolor
80  5.7          2.6         3.5          1.0         versicolor
90  5.5          2.5         4.0          1.3         versicolor
100 5.7          2.8         4.1          1.3         versicolor
110 7.2          3.6         6.1          2.5         virginica 
120 6.0          2.2         5.0          1.5         virginica 
130 7.2          3.0         5.8          1.6         virginica 
140 6.9          3.1         5.4          2.1         virginica 
150 5.9          3.0         5.1          1.8         virginica

In [9]:
length(iris$Sepal.Length)
length(iris)

[1] 150

[1] 5

In [10]:
nrow(iris) # row 수
ncol(iris) # column 수

[1] 150

[1] 5

In [11]:
# iris의 Sepal.Length 의 최대값과 최소값의 차이가 평균보다 큰지 확인
max(iris$Sepal.Length)
min(iris$Sepal.Length)
mean(iris$Sepal.Length) 

(max(iris$Sepal.Length) - min(iris$Sepal.Length)) > mean(iris$Sepal.Length) 

[1] 7.9

[1] 4.3

[1] 5.843333

[1] FALSE

In [12]:
# iris에서 1~10까지의 데이터 중 Sepal.Length와 Sepal.Width만 출력
iris[1:10,1:2]
iris[1:10, c("Sepal.Length", "Sepal.Width")]

Sepal.Length Sepal.Width
1  5.1          3.5        
2  4.9          3.0        
3  4.7          3.2        
4  4.6          3.1        
5  5.0          3.6        
6  5.4          3.9        
7  4.6          3.4        
8  5.0          3.4        
9  4.4          2.9        
10 4.9          3.1

Sepal.Length Sepal.Width
1  5.1          3.5        
2  4.9          3.0        
3  4.7          3.2        
4  4.6          3.1        
5  5.0          3.6        
6  5.4          3.9        
7  4.6          3.4        
8  5.0          3.4        
9  4.4          2.9        
10 4.9          3.1

In [13]:
# 데이터를 처음 받았을 떄
head(iris)
tail(iris) # index 카운트 확인
str(iris) # 컬럼이름, 갯수, 형식 확인 가능, factor 확인
summary(iris) # 중간값과 평균이 차이가 많이 나는지, 최소값 최대값 평균값 으로 데이터의 모양을 파악, 어떻게 수정해야 할지  
# 각각 컬럼별로 따로 놀고있는 데이터들을 연관성있게 정리하는 작업이 정규화이다. (log 등)


Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1          3.5         1.4          0.2         setosa 
2 4.9          3.0         1.4          0.2         setosa 
3 4.7          3.2         1.3          0.2         setosa 
4 4.6          3.1         1.5          0.2         setosa 
5 5.0          3.6         1.4          0.2         setosa 
6 5.4          3.9         1.7          0.4         setosa

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...


  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
       Species  
 setosa    :50  
 versicolor:50  
 virginica :50  
                
                
                

In [14]:
# factor Type인 Species 에서 문자와 숫자로 각각 가져오기
print(as.character(iris$Species))
print(as.numeric(iris$Species))


  [1] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
  [6] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
 [11] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
 [16] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
 [21] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
 [26] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
 [31] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
 [36] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
 [41] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
 [46] "setosa"     "setosa"     "setosa"     "setosa"     "setosa"    
 [51] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [56] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [61] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [66] "versicolor" "versicolor" "versicolor" "versicolor" "versicolor"
 [71] 

---
# 벡터 계산 

In [15]:
x <- c(3,6,9,12,15)
print(x + 1)

[1]  4  7 10 13 16


In [16]:
print(x + 1:5) # 같은 번지수 끼리 더해짐

[1]  4  8 12 16 20


In [17]:
print(x + 1:2) # 이렇게 쓰면 데이터 엉망됨 

Warning message in x + 1:2:
“두 객체의 길이가 서로 배수관계에 있지 않습니다”

[1]  4  8 10 14 16


In [18]:
# 벡터 합치기

x <- c(3,5,6,12,15)
y <- 1:5

append(x,y)

[1]  3  5  6 12 15  1  2  3  4  5

In [19]:
length( append(iris$Sepal.Length, iris$Sepal.Width) )

[1] 300

In [20]:
length( c(iris$Sepal.Length, iris$Sepal.Width) )

[1] 300

In [21]:
# iris의 Sepal.Length의 중복되지 않은 갯수의 percent구하기
print(unique(iris$Sepal.Length))
round(length(unique(iris$Sepal.Length)) / length(iris$Sepal.Length) * 100, 2)
# iris의 Sepal.Length의 중복된 갯수의 percent 구하기
round((length(iris$Sepal.Length) - length(unique(iris$Sepal.Length))) / length(iris$Sepal.Length) * 100 , 2)

 [1] 5.1 4.9 4.7 4.6 5.0 5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.0 6.4 6.9 6.5
[20] 6.3 6.6 5.9 6.0 6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9


[1] 23.33

[1] 76.67

# 문자열 관련 함수 

In [22]:
x <- c('a', 'b', 'c', 'd', 'e')
print(x)
print(x[1:2])
# 합쳐서 출력 
paste(x[1], x[2])

[1] "a" "b" "c" "d" "e"
[1] "a" "b"


[1] "a b"

In [23]:
paste("Hello", "World!")

[1] "Hello World!"

In [24]:
# iris의 1, 51, 101번의 Species 만 한꺼번에 출력하기

paste(iris$Species[1] , ":" , iris$Species[51] , ":", iris$Species[101] )


[1] "setosa : versicolor : virginica"

In [25]:
# 문자열 출력
a <- paste("Hello")
b <- cat("Hello\nWorld!") 
#cat("Hello","\nWorld!")
a # 'Hello'
b # NULL
# cat은 출력만 , paste는 벡터 형성,  cat은 변수선언 불가, paste 변수 지정 가능

Hello
World!

[1] "Hello"

NULL

In [26]:
cat("90\t80\t70")

90	80	70

In [27]:
paste("010","1111","2222", sep="-") # sep 기본값이 한칸 공백 , 변경해서 사용할 수 있다

[1] "010-1111-2222"

# 문자열 추출하기 

In [28]:
str01 <- "abcdefghijklmnop"
substring(str01, 2, 5)
str02 <- "가나다라마바사"
substring(str02, 2,5) 

[1] "bcde"

[1] "나다라마"

In [29]:
# EX : 출력되는 x 중 4와 7 사이에 있는 것은 몇개 인가?
set.seed(123) #난수 고정, 수업에서만 사용 현업에서는 사용 불가
x <- runif(5, 1, 20)
print(x)
sum(x >= 4 & x <=7)

[1]  6.463973 15.977798  8.770562 17.777331 18.868878


[1] 1

# 행렬 (Matrix)

In [30]:
# 행렬 : 2차원 자료를 저장하는 자료형 (Type) 
# 행렬은 데이터 형태가 모두 일치 되어야 구성이 된다. 

# Vector로 행렬 만들기 
vec1 <- c(1,2,3)
vec2 <- c(4,5,6)
vec3 <- c(7,8,9)


In [31]:
# 행으로 붙이기 : rbind (row binding)
mat1 <- rbind(vec1, vec2, vec3) 
# 기존 컬럼 추가 데이터 값이 들어왔을 때 사용

In [32]:
# 열로 붙이기 : cbind (column binding)
mat2 <- cbind(vec1, vec2, vec3)
# 새로운 데이터(컬럼)가 추가되었을 때 사용


In [33]:
# iris의 1~5번 데이터만 추출하여 irisHead라는 변수에 넣기
irisHead <- head(iris, 5)

# irisHead에 새로운 데이터 1,1,1,1,setosa추가하기
irisHead <- rbind(irisHead, c(1,1,1,1,'setosa'))

# irisHead에 abc라는 컬럼과 2,2,2,2,2의 데이터 추가하기
abc <- rep(2,6)
irisHead <- cbind(irisHead, abc)
# irisHead <- cbind(irisHead, abc=rep(2,6)) # 한줄로 끝내기



In [34]:
# iris의 1~5번 데이터만 추출하여 irisHead라는 데이터셋 만들기

irisHead = iris[1:5,]

irisHead <- cbind(irisHead,Length=irisHead$Sepal.Length + irisHead$Petal.Length) # Matrix 방식


> matrix는 모든 type이 같아야 함 (ex. mat1,2), dataframe은 여러 type이 들어갈 수 있음 (ex. iris)

In [35]:
# 컬럼이름 지정해서 추가, 반복 실행해도 여러번 추가되지 않는다.
irisHead$Length <- irisHead$Sepal.Length + irisHead$Petal.Length # dataframe
# 데이터프레임 컬럼 추가할때는 꼭 이렇게 추가해야 한다.

In [36]:
irisHead

Sepal.Length Sepal.Width Petal.Length Petal.Width Species Length
1 5.1          3.5         1.4          0.2         setosa  6.5   
2 4.9          3.0         1.4          0.2         setosa  6.3   
3 4.7          3.2         1.3          0.2         setosa  6.0   
4 4.6          3.1         1.5          0.2         setosa  6.1   
5 5.0          3.6         1.4          0.2         setosa  6.4

In [37]:
# iris 에서 Sepal.Length와 Sepal.Width만 추출하여 irisM이라는 '데이터프레임' 만들기
sl <- iris$Sepal.Length
sw <- iris$Sepal.Width
# 오답 
irisM <- cbind(sl,sw) # 데이터프레임이 아니다. 행렬(Matrix)이다. 
class(irisM)
# 정답
irisM <- as.data.frame(irisM) # 데이터프레임으로 형변환
class(irisM)

[1] "matrix"

[1] "data.frame"

In [38]:
# mat1의 컬럼 이름 추가
mat1
class(mat1)
colnames(mat1) <- c("A","B","C")

[,1] [,2] [,3]
vec1 1    2    3   
vec2 4    5    6   
vec3 7    8    9

[1] "matrix"

In [39]:
mat1D <- as.data.frame(mat1)
class(mat1D)

[1] "data.frame"

In [40]:
# mat2에 row이름 추가
mat2
rownames(mat2) <- 1:3
print(mat2)
mat2D <- as.data.frame(mat2)
class(mat2D)

vec1 vec2 vec3
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

  vec1 vec2 vec3
1    1    4    7
2    2    5    8
3    3    6    9


[1] "data.frame"

In [41]:
# mat1D와 maat2D를 하나의 DataSet으로 만들기
mat1D
colnames(mat2D) <- colnames(mat1D) # 일일이 쓰지 않는다
mat2D

mat3 = rbind(mat1D,mat2D)

mat3D <- as.data.frame(mat3)

print(mat3D)

A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

A B C
1 1 4 7
2 2 5 8
3 3 6 9

     A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9
1    1 4 7
2    2 5 8
3    3 6 9


---
# DataFrame
- 다양한 자료형으로 구성된 2차원 형태의 데이터 구조

In [42]:
# 벡터로 데이터프레임 만들기 
no <- 1:4
name <- c('Apple', 'Banana', 'Peach', 'Berry')
price <- c(500,400,300,200)
qty <- c(5,2,7,9)

In [43]:
# 데이터프레임 ***중요*** 머신러닝, AI는 데이터프레임으로 공부한다 
fruit <- data.frame(no, name, price, qty, stringsAsFactors=F) # stringsAsFactors=F, factor 해제, factor는 문자,숫자 가지고 있음 메모리가 두배
# fruit <- data.frame(번호=no, 상품명=name, 금액=price, 재고량=qty) # 한번에 열 이름까지 변경해서 데이터프레임 생성
colnames(fruit) <- c('번호', '상품명', '금액', '재고량')
fruit

번호 상품명 금액 재고량
1 1    Apple  500  5     
2 2    Banana 400  2     
3 3    Peach  300  7     
4 4    Berry  200  9

In [44]:
str(fruit)
summary(fruit)

'data.frame':	4 obs. of  4 variables:
 $ 번호  : int  1 2 3 4
 $ 상품명: chr  "Apple" "Banana" "Peach" "Berry"
 $ 금액  : num  500 400 300 200
 $ 재고량: num  5 2 7 9


      번호         상품명               금액         재고량    
 Min.   :1.00   Length:4           Min.   :200   Min.   :2.00  
 1st Qu.:1.75   Class :character   1st Qu.:275   1st Qu.:4.25  
 Median :2.50   Mode  :character   Median :350   Median :6.00  
 Mean   :2.50                      Mean   :350   Mean   :5.75  
 3rd Qu.:3.25                      3rd Qu.:425   3rd Qu.:7.50  
 Max.   :4.00                      Max.   :500   Max.   :9.00  

In [45]:
# fruit에서 상품명과 재고량만 보기
fruit[,c("상품명","재고량")]

상품명 재고량
1 Apple  5     
2 Banana 2     
3 Peach  7     
4 Berry  9

In [46]:
# fruit에서 번호를 제외한 모든 내용 보기
fruit[,-1]

상품명 금액 재고량
1 Apple  500  5     
2 Banana 400  2     
3 Peach  300  7     
4 Berry  200  9

In [47]:
# fruit에서 2,4번 행을 제외한 상품명, 금액, 재고량만 출력하기
fruit[-c(2,4),c('상품명','금액','재고량')]

상품명 금액 재고량
1 Apple  500  5     
3 Peach  300  7

In [48]:
# 재고금액 (금액*재고량) 이라는 컬럼 생성하여 fruit에 붙이기
fruit$재고금액 = fruit$금액 * fruit$재고량
fruit


번호 상품명 금액 재고량 재고금액
1 1    Apple  500  5      2500    
2 2    Banana 400  2       800    
3 3    Peach  300  7      2100    
4 4    Berry  200  9      1800

In [49]:
# 원산지 컬럼 추가하기
fruit$원산지 = c('한국','태국','한국','중국')
fruit

번호 상품명 금액 재고량 재고금액 원산지
1 1    Apple  500  5      2500     한국  
2 2    Banana 400  2       800     태국  
3 3    Peach  300  7      2100     한국  
4 4    Berry  200  9      1800     중국

---
# 외부 File 불러오기

In [50]:
# txt file 불러오기
# 데이터 구분이 공백, 탭 일때는 알아서 인식 됨, / 는 구분되지 않으므로 sep = "/"로 구분하는 옵션을 주어야 한다. 
# 헤더 구분을 안하면 컬럼이름으로 쓰인 값들이 chr형식으로 들어가 숫자 데이터도 글자로 인식되어 버린다.
txtEmp <- read.table("../Data/emp.txt", header = T, sep = "/", fileEncoding = 'utf-8', stringsAsFactors = F) # header가 있다
txtEmp


사번 이름 급여
1 101  hong 150 
2 201  lee  250 
3 301  kim  300

In [51]:
str(txtEmp)

'data.frame':	3 obs. of  3 variables:
 $ 사번: int  101 201 301
 $ 이름: chr  "hong" "lee" "kim"
 $ 급여: int  150 250 300


In [52]:
# csv(Comma Seperated Value)
csvEmp <- read.csv("../Data/emp2.csv" , header=F, stringsAsFactors=F)
# 사번, 이름, 급여로 컬럼 변경하기
colnames(csvEmp) = c("사번","이름","급여")
csvEmp
str(csvEmp)

사번 이름   급여
1 101  홍길동 150 
2 102  이순신 450 
3 103  강감찬 500 
4 104  유관순 350 
5 105  김유신 400

'data.frame':	5 obs. of  3 variables:
 $ 사번: int  101 102 103 104 105
 $ 이름: chr  "홍길동" "이순신" "강감찬" "유관순" ...
 $ 급여: int  150 450 500 350 400


> 4/26 수업 끗

In [2]:
df <- data.frame(x=1:5, y=seq(2,10,2), z=c('a','b','c','d','e'))
df

x y  z
1 1  2 a
2 2  4 b
3 3  6 c
4 4  8 d
5 5 10 e

In [3]:
# x컬럼의 합계는 15이고 y컬럼의 합계는 30입니다
cat("x컬럼의 합계는", sum(df$x),"이고 y컬름의 합계는", sum(df$y),"입니다.")

x컬럼의 합계는 15 이고 y컬름의 합계는 30 입니다.

### 함수를 부르는 함수

In [4]:
# 데이터 프레임에 함수 적용 (열방향) # 가로방향 1, 세로방향 2 # 데이터가 엄청 많을떄는 apply를 써야한다
apply(df[,1:2], 2, sum)
apply(df[,1:2], 2, mean)
apply(df[,1:2], 2, sd)

x  y 
15 30

x y 
3 6

x        y 
1.581139 3.162278

In [56]:
# 데이터프레임에 함수 적용 (행방향)
apply(df[,1:2], 1, sum)
apply(df[,1:2], 1, mean)
apply(df[,1:2], 1, sd)

[1]  3  6  9 12 15

[1] 1.5 3.0 4.5 6.0 7.5

[1] 0.7071068 1.4142136 2.1213203 2.8284271 3.5355339

In [5]:
# df에 Hap이라는 컬럼을 만들어서 행방향의 합계 구하기
df$Hap <- apply(df[,1:2] , 1, sum)

df

x y  z Hap
1 1  2 a  3 
2 2  4 b  6 
3 3  6 c  9 
4 4  8 d 12 
5 5 10 e 15

In [60]:
# 부분집합 쵸큼중요 # subset( 어디에서, 조건 )
subset(df, x >= 3) 
subset(df, x >= 3 & y >= 8) 

x y  z Hap
3 3  6 c  9 
4 4  8 d 12 
5 5 10 e 15

x y  z Hap
4 4  8 d 12 
5 5 10 e 15

In [6]:
# 조건을 계속 붙여서 원하는 모습으로 볼 수 있다.
subset(df, x >= 3 & y >= 8)
subset(df, x >= 3 & y >= 8)[ , 1:2]
subset(df, x >= 3 & y >= 8)[ , 1:2][ , 1]

# 4번행과 5번행의 x컬럼과 y컬럼의 합계를 구하기
apply(subset(df, x >= 3 & y >= 8)[,1:2] , 2, sum)
apply(subset(df, x >= 3 & y >= 8)[,1:2] , 2, sum)[1]

x y  z Hap
4 4  8 d 12 
5 5 10 e 15

x y 
4 4  8
5 5 10

[1] 4 5

x  y 
 9 18

x 
9

---
### 두개 이상의 데이터프레임 병합하기
#### sql의 join과 비슷

In [12]:
# Case 1 : Key값이 되는 컬럼이 동일하고, data의 갯수도 동일한 경우 (데이터 정제가 잘 되있는 경우)
height <- data.frame(id=1:3, height=c(160, 170, 180)) ; height
weight <- data.frame(id=c('2','1','3'), weight=c(70,60,80)) ; weight

id height
1 1  160   
2 2  170   
3 3  180

id weight
1 2  70    
2 1  60    
3 3  80

In [11]:
# 병합
merge(height,weight)

id height weight
1 1  160    60    
2 2  170    70    
3 3  180    80

In [13]:
# Case 2 : key값이 되는 컬럼이 동일하지 않고 , 각각의 data 갯수도 다를 경우
height <- data.frame(id=1:3, height=c(160,170,180)) ; height
weight <- data.frame(ad=c(2,1) , weight=c(70,60)) ; weight

id height
1 1  160   
2 2  170   
3 3  180

ad weight
1 2  70    
2 1  60

In [14]:
# 그냥 병합
## 중복되면서 나온다
merge(height,weight) 

id height ad weight
1 1  160    2  70    
2 2  170    2  70    
3 3  180    2  70    
4 1  160    1  60    
5 2  170    1  60    
6 3  180    1  60

In [15]:
# key를 정의하기 : data가 적은 쪽의 기준으로 merge 한다. (교집합)
## by. : key 값이라고 알려준다. 
merge(x=height, y=weight, by.x='id', by.y='ad')

id height weight
1 1  160    60    
2 2  170    70

In [16]:
# data가 많은 쪽의 기준으로 merge (합집합) ## 보통 이걸로 사용
# 옵션 추가  all.x = T : x는 모두 보여준다 true
merge(x=height, y=weight, by.x='id', by.y='ad', all.x = T)

id height weight
1 1  160    60    
2 2  170    70    
3 3  180    NA

### 행렬 함수로 행렬 만들기

In [17]:
matrix(1:10)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [18]:
matrix(1:10, nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [21]:
matrix(1:10, nrow=3, ncol=3)
matrix(1:10, ncol=3)
matrix(1:10, nrow=3) 
# 벡터는 빈 값 두지 않음, 반복해서 채운다

Warning message in matrix(1:10, nrow = 3, ncol = 3):
“데이터의 길이[10]가 행의 개수[3]의 배수가 되지 않습니다”

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

Warning message in matrix(1:10, ncol = 3):
“데이터의 길이[10]가 행의 개수[4]의 배수가 되지 않습니다”

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7     1  
[4,] 4    8     2

Warning message in matrix(1:10, nrow = 3):
“데이터의 길이[10]가 행의 개수[3]의 배수가 되지 않습니다”

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8     1  
[3,] 3    6    9     2

### List
- Type이 다른 자료구조로 생성이 가능하다
- key와 value 값으로 구성된다 
- java의 딕셔너리 ?

In [26]:
member <- list(name='홍길동', address='서울', Tel='010-1111-2222' ,pay=300)
member
member$name

$name
[1] "홍길동"

$address
[1] "서울"

$Tel
[1] "010-1111-2222"

$pay
[1] 300

[1] "홍길동"

In [27]:
# 컬럼 추가
member$birth <- '1998-08-08'
member

$name
[1] "홍길동"

$address
[1] "서울"

$Tel
[1] "010-1111-2222"

$pay
[1] 300

$birth
[1] "1998-08-08"

---
# 문자열 처리
수집한 데이터의 필요한 문자열을 자르고, 교체하고, 추출하는 작업 : 데이터 정제

패키지 이용 ( 자바의 import ) , 한 PC에 한번만 설치하면 된다. 사용하려면 불러오기는 해야함
### stringr package 사용
- str_length() : 문자열 길이
- str_c() : 문자열 연결
- str_sub() : 범위에 해당하는 문자열 생성
- str_split() : 구분자를  기준으로 문자열을 분리하여 부분 생성
- str_replace() : 문자열에서 기존 문자열을 특정 문자열로 변환 / str_replace_all() # 천단위 쉼표가 있는 데이터 '123,456' 1) replace(_all)으로 , 를 공백으로 바꾼다 2) as.numeric으로 문자열데이터를 숫자로 바꾼다 
- str_extract() : 문자열에서 특정 문자열 패턴의 첫번째 문자열 추출 / str_extract_all()
- str_locate() : 문자열에서 특정 문자열 패턴의 첫번째 위치 추출 / str_locate_all()

In [29]:
# 패키지 불러오기
library(stringr)

In [30]:
string <- 'hongkildong105yoube1002kwanwoo25장비2005'

In [41]:
# a-z 까지의 영문자가 연속으로 3개 발견된 문자열 추출 ## 정규식 사용
print(str_extract_all(string, "[a-z]{3}"))


[[1]]
[1] "hon" "gki" "ldo" "you" "kwa" "nwo"



In [43]:
# a-z 까지의 영문자가 연속으로 3-5개 발견된 문자열 추출 
str_extract_all(string, "[a-z]{3,5}")

[[1]]
[1] "hongk" "ildon" "yoube" "kwanw"

In [51]:
# a-z 까지의 영문자가 연속으로 1개이상 발견된 문자열 추출 
aaa <- str_extract_all(string, "[a-z]{1,}")

class(aaa) # list
bbb <- unlist(aaa) # list형식 해제
class(bbb)
bbb[1]

[1] "list"

[1] "character"

[1] "hongkildong"

In [60]:
# string에서 숫자만 출력하여 합계 구하기
str_extract_all(string, "[0-9]{1,}")
sum(as.numeric(unlist(str_extract_all(string, "[0-9]{1,}"))))

[[1]]
[1] "105"  "1002" "25"   "2005"

[1] 3137

In [62]:
# 한글만 추출하기
str_extract_all(string, "[가-힣]{1,}")

[[1]]
[1] "장비"

In [65]:
# 영문자를 제외한 문자 출력하기
str_extract_all(string, "[^a-z]{1,}")

[[1]]
[1] "105"        "1002"       "25장비2005"

In [66]:
# 문자열 길이 구하기
str_length(string)

[1] 38

In [67]:
# 문자열 위치 구하기
str_locate(string, "장비")

start end
[1,] 33    34

In [73]:
# 부분 문자열 추출
str_sub(string, 1, 32)
str_locate(string, '장비')[1]

# '장비'의 위치가 유동적일때
str_sub(string, 1, str_locate(string, '장비')[1] - 1)

[1] "hongkildong105yoube1002kwanwoo25"

[1] 33

[1] "hongkildong105yoube1002kwanwoo25"

In [75]:
# 대문자, 소문자 변경하기
str_to_upper(string)
str_to_lower(string)


[1] "HONGKILDONG105YOUBE1002KWANWOO25장비2005"

[1] "hongkildong105yoube1002kwanwoo25장비2005"

In [84]:
# 문자열 교체하기
string <- str_replace(string, 'hongkildong105', '홍길동35,')
string <- str_replace(string, 'yoube1002' , '유비45,')
string <- str_replace(string, 'kwanwoo25' , '관우25,')
string <- str_replace(string, '2005' , '20')
string

[1] "홍길동35,유비45,관우25,장비20"

In [85]:
# 문자열 분리하기
str_split(string, ',')

[[1]]
[1] "홍길동35" "유비45"   "관우25"   "장비20"

In [89]:
# 천단위 쉼표가 들어간 문자열을 숫자열로 변경하기
price <- '123,456,789'

p <- as.numeric(str_replace_all(price, ',', ''))
class(p)

[1] "numeric"